const LP_CONFIG={lpName:'softbank-hikari-entry',carrier:'SoftBank 光',device:matchMedia('(max-width:767px)').matches?'mobile':'desktop'};
const KEYS=['utm_source','utm_medium','utm_campaign','utm_term','utm_content','gclid','gbraid','wbraid','yclid','msclkid','fbclid'];
const form=document.querySelector('#application-form'),panels=[...form.querySelectorAll('.form-panel')],progress=[...form.querySelectorAll('.form-progress span')],storeKey=LP_CONFIG.lpName+':attribution';
function attribution(){const q=new URLSearchParams(location.search);let d={};try{d=JSON.parse(sessionStorage.getItem(storeKey)||'{}')}catch{}KEYS.forEach(k=>{if(q.has(k))d[k]=q.get(k)||''});if(!d.entry_url)d.entry_url=location.href;if(!d.entry_time)d.entry_time=new Date().toISOString();if(!d.referrer)d.referrer=document.referrer;Object.assign(d,{submit_url:location.href,lp_name:LP_CONFIG.lpName,carrier:LP_CONFIG.carrier,device:LP_CONFIG.device});try{sessionStorage.setItem(storeKey,JSON.stringify(d))}catch{}return d}
function tracking(){const h=document.querySelector('#tracking-fields');h.innerHTML='';Object.entries(attribution()).forEach(([n,v])=>{const i=document.createElement('input');i.type='hidden';i.name=n;i.value=v;h.append(i)})}
function val(n){return form.querySelector(`[name="${n}"]:checked`)?.value||''}
function show(n){panels.forEach(p=>{const a=p.dataset.formStep==String(n);p.hidden=!a;p.classList.toggle('active',a)});const s=n==='review'?1:n==='complete'?2:0;progress.forEach((p,i)=>p.classList.toggle('active',i<=s));form.scrollIntoView({behavior:'smooth',block:'start'})}
function setError(control,message){control.classList.toggle('invalid',Boolean(message));let error=control.nextElementSibling;if(!error?.classList.contains('field-error')){error=document.createElement('small');error.className='field-error';control.insertAdjacentElement('afterend',error)}error.textContent=message;return !message}
function setGroupError(name,message){const group=form.querySelector(`[name="${name}"]`).closest('.segmented');return setError(group,message)}
document.querySelectorAll('[data-procedure]').forEach(b=>b.onclick=()=>{const t=form.querySelector(`[name="procedure"][value="${b.dataset.procedure}"]`);if(t)t.checked=true;document.querySelectorAll('[data-procedure]').forEach(x=>x.classList.toggle('selected',x===b));form.scrollIntoView({behavior:'smooth'})});
form.querySelector('.next-step').onclick=()=>{const checks=[setGroupError('procedure',val('procedure')?'':'希望する手続きを選択してください。'),setError(form.elements.current_line,form.elements.current_line.value?'':'現在利用中の回線を選択してください。'),setGroupError('moving',val('moving')?'':'引っ越し予定を選択してください。')];const ok=checks.every(Boolean);document.querySelector('#step1-error').textContent=ok?'':'赤く表示された項目をご確認ください。';if(ok)show(2)};
form.querySelector('.back-step').onclick=()=>show(1);form.querySelector('.back-to-edit').onclick=()=>show(2);
const postal=form.querySelector('#postal'),address=form.querySelector('#address'),postalStatus=document.querySelector('#postal-status');let postalRequest=0;
postal.oninput=async e=>{e.target.value=e.target.value.replace(/\D/g,'').slice(0,7);setError(postal,'');postalStatus.className='postal-status';postalStatus.textContent='';if(e.target.value.length!==7)return;const request=++postalRequest;postalStatus.textContent='住所を検索しています…';try{const response=await fetch('https://zipcloud.ibsnet.co.jp/api/search?zipcode='+encodeURIComponent(e.target.value));if(!response.ok)throw new Error();const data=await response.json();if(request!==postalRequest)return;if(data.results?.length){const r=data.results[0];address.value=r.address1+r.address2+r.address3;setError(address,'');postalStatus.textContent='住所を自動入力しました。番地・建物名を追記してください。';postalStatus.classList.add('success')}else{postalStatus.textContent='住所が見つかりません。住所を手入力してください。';postalStatus.classList.add('error')}}catch{if(request!==postalRequest)return;postalStatus.textContent='自動検索できませんでした。住所を手入力してください。';postalStatus.classList.add('error')}};
form.querySelector('.review-step').onclick=()=>{const name=form.elements.customer_name.value.trim(),phone=form.elements.phone.value.replace(/\D/g,''),time=form.elements.contact_time.value,postalValue=postal.value,addressValue=address.value.trim();const checks=[setError(form.elements.customer_name,name?'':'お名前を入力してください。'),setError(form.elements.phone,/^0\d{9,10}$/.test(phone)?'':'電話番号を10〜11桁の数字で入力してください。'),setError(form.elements.contact_time,time?'':'希望連絡時間を選択してください。'),setError(postal,/^\d{7}$/.test(postalValue)?'':'郵便番号を7桁の数字で入力してください。'),setError(address,addressValue?'':'利用予定住所を入力してください。')];const ok=checks.every(Boolean);document.querySelector('#step2-error').textContent=ok?'':'赤く表示された項目をご確認ください。';if(!ok){form.querySelector('.invalid')?.focus();return}const rows=[['希望する手続き',val('procedure')],['現在利用中の回線',form.elements.current_line.value],['引っ越し予定',val('moving')],['お名前',name],['電話番号',phone],['希望連絡時間',time],['郵便番号',postalValue],['利用予定住所',addressValue]];document.querySelector('#review-list').innerHTML=rows.map(([k,v])=>`<div><dt>${k}</dt><dd>${v}</dd></div>`).join('');tracking();show('review')};
form.onsubmit=e=>{e.preventDefault();tracking();show('complete')};
form.addEventListener('input',e=>{if(e.target.matches('input:not([type="radio"]),select')&&e.target.value)setError(e.target,'')});form.addEventListener('change',e=>{if(e.target.type==='radio')setGroupError(e.target.name,'')});
const sticky=document.querySelector('.sticky'),visible={hero:true,form:false,final:false,footer:false},update=()=>sticky.classList.toggle('hidden',visible.hero||visible.form||visible.final||visible.footer);[['hero','.hero'],['form','#application'],['final','#final-cta'],['footer','#footer']].forEach(([k,s])=>new IntersectionObserver(([e])=>{visible[k]=e.isIntersecting;update()},{threshold:.08}).observe(document.querySelector(s)));tracking();update();
